goog.provide('fonzie.RulerFont');

/**
 * @const
 * @type {fonzie.Font}
 */
fonzie.RulerFont = new fonzie.Font({
    family: '__ruler__',
    src: {
        woff: 'data:application/x-font-woff;base64,' +
              'd09GRgABAAAAAAOwAA8AAAAABTAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABWAAAABwA' +
              'AAAcYWCdE0dERUYAAAF0AAAAHAAAACAAMgAET1MvMgAAAZAAAABAAAAAVmK/U2NjbWFwAAAB0AAA' +
              'AEkAAAFKv6sklGN2dCAAAAIcAAAABAAAAAQAiAoiZ2FzcAAAAiAAAAAIAAAACP//AANnbHlmAAAC' +
              'KAAAABYAAAAgAAJqBmhlYWQAAAJAAAAAKAAAADb29XMVaGhlYQAAAmgAAAAaAAAAJA2GFNJobXR4' +
              'AAAChAAAABQAAAAUQPoAAGxvY2EAAAKYAAAADAAAAAwACAAQbWF4cAAAAqQAAAAdAAAAIABIAAdu' +
              'YW1lAAACxAAAALUAAAFAFccyQ3Bvc3QAAAN8AAAAKQAAAELmXGWbd2ViZgAAA6gAAAAGAAAABuaN' +
              'T8UAAAABAAAAAMmJbzEAAAAAy+uW1QAAAADL65cMeNpjYGRgYOADYgkGEGBiYARCFjAG8RgABHYA' +
              'N3jaY2AUqWWcwMDKwMJqzDqLgYFRDkIzX2dIYxJiYGBiYOVkgAFGBiQQkOaawuDAkPmAgS3tXxrD' +
              'DmQ1AJuHCdB42mNgYGBmgGAZBkYGEHAB8hjBfBYGDSDNBqQZGZgYMh8w/P8P5IPp/7MUWKDqgYCR' +
              'jQHOYWQCEkwMqICRgXqAmWFQAgADwwkeAAAAAIgKIgAAAAH//wACeNpjYGRAAoYMDAg+MwODJTMA' +
              'BEQAcwAAeNpjYGRgYADi6ovL58Tz23xl4OZgAIHTr6fzINNQwMHABKIAK60JAHjaY2BkYOA58+cM' +
              'ww4JBihgZEAFrABlDQN4AAAIAAAACAAAAAgAAAAYAAAAEPoAAAAAAAAAAAAAAAgAEHjaY2BkYGBg' +
              'ZWBhANEMDExAzAhmO4D5DAADOwBQAAAAeNpVj7EOAVEQRc/aJSiUIqr3A4SVVWyp0GkUJLoVSyRC' +
              'sij8gtpX+BL+yt23T5ZiZu6dd+fOPKDOFh8vaODRBIcrtMQK7DOh43BAl5XDVdpcHK5JfXf4pf7D' +
              '4TcDnmRcOZCqzpV3liViU04c5ZHXTP0UQ0hfM4ZYUc4VfKSXHpEiFBoq/yr+vRe2e2Zvdxipc99S' +
              'v1Re6+/FBd/3vLsRm8nj5jYaRaT9oTSxYmyvtPs/g8coKwAAAHjaY2BiwA9YGRgYmRiZGXwYWdjS' +
              'cyoLMgwhlBF7aV6mq4GBAQBcTgc/AAAAAAFPxeaMAAA=',
        ttf:  'data:font/truetype;base64,' +
              'AAEAAAAPAIAAAwBwRkZUTWFgnRMAAAD8AAAAHEdERUYAMgAEAAABGAAAACBPUy8yYr9TYwAAATgA' +
              'AABWY21hcL+rJJQAAAGQAAABSmN2dCAAiAoiAAAC3AAAAARnYXNw//8AAwAAAuAAAAAIZ2x5ZgAC' +
              'agYAAALoAAAAIGhlYWT29XMVAAADCAAAADZoaGVhDYYU0gAAA0AAAAAkaG10eED6AAAAAANkAAAA' +
              'FGxvY2EACAAQAAADeAAAAAxtYXhwAEgABwAAA4QAAAAgbmFtZRXHMkMAAAOkAAABQHBvc3TmXGWb' +
              'AAAE5AAAAEJ3ZWJm5o1PxQAABSgAAAAGAAAAAQAAAADJiW8xAAAAAMvrltUAAAAAy+uXDAABAAAA' +
              'DgAAABgAAAAAAAIAAQABAAQAAQAEAAAAAgAAAAEUfQGQAAUABAUzBZoAAAEeBTMFmgAAA9cAZgIS' +
              'AAACAAUJAAAAAAAAAAAAAQAAAAAAAAAAAAAAAFBmRWQAQABp4AAGZv5mALgAAAAAAAAAAQAAAAAA' +
              'AAAAAAMAAAADAAAAHAABAAAAAABEAAMAAQAAABwABAAoAAAABgAEAAEAAgBp4AD//wAAAGngAP//' +
              '/5ogBAABAAAAAAAAAAABBgAAAQAAAAAAAAABAgAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAA' +
              'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
              'AAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
              'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
              'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgKIgAAAAH/' +
              '/wACAAEAAAAAAAAAAAAAAAAxAAABAAAAAAAAAAAAAwAAOQMAAQAAAAEAAHvRp5xfDzz1AAsIAAAA' +
              'AADL65cMAAAAAMvrlwwAAAAAAAAAAAAAAAgAAgAAAAAAAAABAAAMzPzMALgYAAAAAAAAAAABAAAA' +
              'AAAAAAAAAAAAAAAABQgAAAAIAAAACAAAABgAAAAQ+gAAAAAAAAAAAAAACAAQAAEAAAAFAAQAAQAA' +
              'AAAAAgAAAAEAAQAAAEAAAAAAAAAAAAAIAGYAAwABBAkAAQAKAAAAAwABBAkAAgAOAAoAAwABBAkA' +
              'AwBCABgAAwABBAkABAAaAFoAAwABBAkABQAWAHQAAwABBAkABgAKAIoAAwABBAkAyAAWAJQAAwAB' +
              'BAkAyQAwAKoAcgB1AGwAZQByAFIAZQBnAHUAbABhAHIARgBvAG4AdABGAG8AcgBnAGUAIAAyAC4A' +
              'MAAgADoAIAByAHUAbABlAHIAIAA6ACAAMwAwAC0ANQAtADIAMAAxADIAcgB1AGwAZQByACAAUgBl' +
              'AGcAdQBsAGEAcgBWAGUAcgBzAGkAbwBuACAAMQAuADAAcgB1AGwAZQByAFcAZQBiAGYAbwBuAHQA' +
              'IAAxAC4AMABXAGUAZAAgAE0AYQB5ACAAMwAwACAAMAA1ADoAMgAxADoAMQA2ACAAMgAwADEAMgAC' +
              'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAECAQMATAEEBmdseXBoMQZnbHlwaDIH' +
              'dW5pRTAwMAAAAAFPxeaMAAA='
    }
});
